language: node_js
node_js:
- '0.11'
before_install:
- npm install grunt-cli bower -g
- bower install
script: grunt
deploy:
  provider: releases
  api_key:
    secure: S+zUz2vut9Ypf3CW8QsmoTJ2zinujmmRTj8aNjUic2yRQMztC1vFMAUU5jRgrkifPljiPciOgasepCII3yb/lF+6zBgFpEy1qAtCwVAKpVv2JjbboQ9uvbXXR51V2vBG89P2Yc4QhTDYQs6o33okRnPXDrE3uGJNXUIQpjKo+c4lDd7EWmWML06Vxgg490MHx2cOaSld8akNaboWritqND7IYhP6QaPfcKAa6tw9E5wC/N2OZiGzXOzcJUApFIRL+TAtWxj7KFqXDve3Z7LULdfoiWvYng48DOCHGLkZWi9owWhjxYS65wUbjbS6hMCn2nSz/STwX9hyk7j+LKD9DoYnhAHpIRbg0px5K9rhAYX0S1AdgFzW8e1Iwz9fCCkbeXeLPkn7xnTGlsxvgTMaI0W/2pc6dlje+UTi5qfFy/xAeDgDqtGz6c360RDusl3W+WIwUmLRkkdhC+rnxt7038ImG9gm3m5dsYZ8CjWBX8B7cN3TdJHK98/pIutMlWQ+S+GATCm0uW7Tp8WtJTlrfOu6d0yXNWnvbx+iQSluzp31VwHw7Ro5pbQ8a/5eDpnY70HeRvSITgv3SvQPDayqzeMsxvLtNGbuHYek36CqeIF2M5PWHNPr6P+Z0vpcobUdx88x+FGLUdIfLR47pql/bifkb20eG7TckRWA2C8lRek=
  file: dist/*
  skip_cleanup: true
  on:
    repo: tdukart/wedgeWheel
    tags: true